print("Enter x")
x = int(input())
print("Enter y")
y = int(input())
print(x+y)
print(x-y)
result = (x*y)
print("Значення виразу 'x*y' =", result)
print("Ділене = ", x, "Дільник = ", y, "Частка =", x/y)

#  а чому не все однорідно? Маю на увазі: або все через прінт, або через змінні як result?  (review G.Patenko)
